# Generated by Django 4.1.7 on 2023-03-10 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="followers",
            field=models.ManyToManyField(
                related_name="followed_books",
                through="books.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
