# Generated by Django 4.1.7 on 2023-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_available_aux",
            field=models.BooleanField(default=True),
        ),
    ]
