# Generated by Django 4.1.7 on 2023-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_book_is_available_aux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
