# Generated by Django 4.1.7 on 2023-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
