# Generated by Django 4.1.7 on 2023-03-13 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_alter_book_is_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="is_available",
            new_name="is_avaliable",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="is_available_aux",
            new_name="is_avaliable_aux",
        ),
    ]
