# Generated by Django 4.1.7 on 2023-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lending",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
