# Generated by Django 4.1.7 on 2023-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="book_is_avaliable",
            field=models.BooleanField(default=True),
        ),
    ]
