# Generated by Django 4.1.7 on 2023-03-08 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="qtd_book",
        ),
    ]
