# Generated by Django 4.1.7 on 2023-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0003_copy_book_is_avaliable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="book_is_avaliable",
        ),
    ]
