# Generated by Django 4.1.7 on 2023-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0004_remove_copy_book_is_avaliable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="is_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lending",
            name="return_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
